### ISSUE TITLE
Make an edited logo for KOBUGE-Incubator

### ISSUE THREAD

**Issue by akien-mga** [KOBUGE-Games/logo#3]
This one is mostly for @fry-, we need to give you some work to make sure you stay awake :-D

We created the @KOBUGE-Incubator organisation for older projects that nobody in the core team is working on, and to welcome new project ideas by Kobuge community members. The idea is that projects that grow to be mature in the incubator could be made officially maintained Kobuge projects, just like Herbi a few weeks ago. And projects that nobody seems to care about anymore like Ringed can rest in peace in the incubator until someone shows up to revive them :)

For the incubator, we need a new logo to differentiate it from the @KOBUGE-Games logo. A simple edited version of the current logo would be nice, to show the affiliation.

@bojidar-bg proposed to put the Kobuge pad/star in an half-hatched egg to illustrate the "incubator" concept :)

**Comment by fry-** [comment]
how about this:
![kobuge_incubator](https://cloud.githubusercontent.com/assets/10758005/14409870/e8de55a0-ff1f-11e5-99c9-c4c7333794ce.png)

**Comment by ObaniGemini** [comment]
Lol
:+1:

**Comment by akien-mga** [comment]
That's awesome! :D

**Comment by bojidar-bg** [comment]
@akien-mga ~ Note that the logo is now live on the org. (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd> to force cache clear)

Close if you consider it done.

**Comment by akien-mga** [comment]
I'll just keep it open until added to this git repo (could do it tonight).

**Comment by fry-** [comment]
Thanks for the nice feedback guys :smile: 
closed by 8ca7d8ceeb7c349770657370096ac285b365c509
